version: 0.2
env:
    parameter-store:
        API_KEY: /CodeBuild/API_KEY

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - 'touch .npmignore'
            - 'npm install -g gatsby'
    pre_build:
        commands:
            - 'npm ci --production'
            - sed -i "s/API_KEY_PLACEHOLDER/$API_KEY/g" src/@lekoarts/gatsby-theme-minimal-blog/texts/MyComponent.js
    build:
        commands:
            - 'npm run-script build'
    post_build:
        commands:
            - 'npm run-script deploy'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/*'
        - 'public/*'
